"$schema" = "./node_modules/wrangler/config-schema.json"
name = "vetlist"
compatibility_date = "2026-04-20"
main = "./worker/index.js"
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[[routes]]
pattern = "vetlist.org"
zone_name = "vetlist.org"
custom_domain = true

[[routes]]
pattern = "www.vetlist.org"
zone_name = "vetlist.org"
custom_domain = true
